### ISSUE TITLE
Can't pip install as of v1.0.1

### ISSUE THREAD

**Issue by technotariat** [uucidl/uu.xunitgen#9]
Hi,

Since the update to v1.0.1 on PyPi pip is unable to install xunitgen due to `README.rst` not being found.

## Stack trace from pip
```
Collecting xunitgen
  Downloading xunitgen-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1Zv3l3/xunitgen/setup.py", line 13, in <module>
        long_description=open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
```

## Filelisting of tarball from PyPi
```
$ tar -tvf xunitgen-1.0.1.tar.gz
drwxrwxrwx 0/0               0 2017-12-10 12:52 xunitgen-1.0.1/
-rw-rw-rw- 0/0            3513 2017-12-10 12:52 xunitgen-1.0.1/PKG-INFO
-rw-rw-rw- 0/0             382 2017-12-10 12:52 xunitgen-1.0.1/setup.py
drwxrwxrwx 0/0               0 2017-12-10 12:52 xunitgen-1.0.1/xunitgen/
-rw-rw-rw- 0/0            1856 2017-12-10 11:58 xunitgen-1.0.1/xunitgen/disk_writing.py
-rw-rw-rw- 0/0            3482 2017-12-10 11:58 xunitgen-1.0.1/xunitgen/event_traces.py
-rw-rw-rw- 0/0            4729 2017-12-10 12:16 xunitgen-1.0.1/xunitgen/main.py
-rw-rw-rw- 0/0            1902 2017-12-10 11:58 xunitgen-1.0.1/xunitgen/step_recording.py
-rw-rw-rw- 0/0             153 2017-12-10 11:58 xunitgen-1.0.1/xunitgen/__init__.py
```

Think the README needs to be added to the files to collect when bundling the project.

**Comment by uucidl** [comment]
Thanks for having reported and file the issue, it should now be fixed with 1.0.3
